{
  "______________网站升级中\n": "              网站升级中\n",
  "______________预计于\n": "              预计于\n",
  "______________恢复服务，感谢您的耐心等候。\n": "              恢复服务，感谢您的耐心等候。\n",
  "未推荐影片": "未推荐影片",
  "推荐": "推荐",
  "取消推荐": "取消推荐",
  "已推荐影片": "已推荐影片",
  "//获取管理员审核推荐作品（recommend）\n": "//获取管理员审核推荐作品（recommend）\n",
  "//获取管理员推荐作品\n": "//获取管理员推荐作品\n",
  "//_未推荐电影列表更新recommend情况\n": "// 未推荐电影列表更新recommend情况\n",
  "//_推荐电影列表更新recommend情况\n": "// 推荐电影列表更新recommend情况\n",
  "_用户协议_": " 用户协议 ",
  "____//_如果_router_是_image\n": "    // 如果 router 是 image\n",
  "____//_如果_router_是_film\n": "    // 如果 router 是 film\n",
  "_logo_&_社区页面_": " logo & 社区页面 ",
  "________________全球_ai_电影大赛\n": "                全球 AI 电影大赛\n",
  "________________即刻参与\n": "                即刻参与\n",
  "_工具栏_": " 工具栏 ",
  "_登陆后_": " 登陆后 ",
  "_用户_": " 用户 ",
  "_有头像_": " 有头像 ",
  "_无头像，使用默认头像_": " 无头像，使用默认头像 ",
  "_更多_": " 更多 ",
  "_登录_": " 登录 ",
  "_主题模式_": " 主题模式 ",
  "_语言_": " 语言 ",
  "________________________中文\n": "                        中文\n",
  "//_退出\n": "// 退出\n",
  "//切换语言\n": "//切换语言\n",
  "________language:_'zh-cn',_//_设置语言\n": "        language: 'zh-CN', // 设置语言\n",
  "________preload:_'auto',_//_预加载\n": "        preload: 'auto', // 预加载\n",
  "________//_fluid:_true,_//_自适应宽高，不能！如果设置了，则会少一截\n": "        // fluid: true, // 自适应宽高，不能！如果设置了，则会少一截\n",
  "________src:_props.src,_//_要嵌入的视频源的源_url\n": "        src: props.src, // 要嵌入的视频源的源 URL\n",
  "________poster:_props.poster,_//_视频封面\n": "        poster: props.poster, // 视频封面\n",
  "________controls:_props.controls_?_props.controls_:_true,_//_是否显示控制条\n": "        controls: props.controls ? props.controls : true, // 是否显示控制条\n",
  "________autoplay:_props.autoplay_?_props.autoplay_:_false,_//_是否自动播放\n": "        autoplay: props.autoplay ? props.autoplay : false, // 是否自动播放\n",
  "________muted:_props.muted_?_props.muted_:_false,_//_是否静音\n": "        muted: props.muted ? props.muted : false, // 是否静音\n",
  "________loop:_props.loop_?_props.loop_:_false,_//_是否循环播放\n": "        loop: props.loop ? props.loop : false, // 是否循环播放\n",
  "_爆款视频_": " 爆款视频 ",
  "_电影创作_": " 电影创作 ",
  "_图片生成_": " 图片生成 ",
  "_视频生成_": " 视频生成 ",
  "_音乐生成_": " 音乐生成 ",
  "_图片说话_": " 图片说话 ",
  "_图片抠图_": " 图片抠图 ",
  "电脑访问_filmaction.ai": "电脑访问 filmaction.ai",
  "体验更多精彩内容": "体验更多精彩内容",
  "________________________全球_ai_电影大赛\n": "                        全球 AI 电影大赛\n",
  "________________________即刻参与\n": "                        即刻参与\n",
  "document.title_=_'创作工具';\n": "document.title = '创作工具';\n",
  "_角色描述_": " 角色描述 ",
  "_操作_": " 操作 ",
  "_ai_生成角色形象描述_": " AI 生成角色形象描述 ",
  "_删除角色_": " 删除角色 ",
  "_角色图_": " 角色图 ",
  "_第一次生成按钮_": " 第一次生成按钮 ",
  "_重新生成按钮_": " 重新生成按钮 ",
  "//_创建一个防抖函数，每隔_50ms_执行一次\n": "// 创建一个防抖函数，每隔 50ms 执行一次\n",
  "//_处理失去焦点事件\n": "// 处理失去焦点事件\n",
  "//_处理粘贴事件\n": "// 处理粘贴事件\n",
  "_标题_": " 标题 ",
  "_故事_": " 故事 ",
  "____________故事\n": "            故事\n",
  "_角色_": " 角色 ",
  "____________角色\n": "            角色\n",
  "____________________新增角色\n": "                    新增角色\n",
  "_脚本、分镜、视频、旁白、配音_": " 脚本、分镜、视频、旁白、配音 ",
  "____________脚本\n": "            脚本\n",
  "_配乐_": " 配乐 ",
  "____________配乐\n": "            配乐\n",
  "_成片_": " 成片 ",
  "____________成片\n": "            成片\n",
  "_设置_": " 设置 ",
  "____________设置\n": "            设置\n",
  "________show_toast_duration('标题不能为空！',_3000)\n": "        show_toast_duration('标题不能为空！', 3000)\n",
  "________________加载更多\n": "                加载更多\n",
  "____<n-modal_v-model:show=\"delete_modal_visibility\"_title=\"删除影片\"_preset=\"card\"\n": "    <n-modal v-model:show=\"delete_modal_visibility\" title=\"删除影片\" preset=\"card\"\n",
  "________________确认删除\n": "                确认删除\n",
  "________________生成副本\n": "                生成副本\n",
  "________________另存为副本\n": "                另存为副本\n",
  "________________下载素材\n": "                下载素材\n",
  "________________下载所有素材\n": "                下载所有素材\n",
  "_作品可见性_": " 作品可见性 ",
  "____________________作品可见性\n": "                    作品可见性\n",
  "____________________________class=\"text-sm_text-neutral-500_ms-2_dark:text-neutral-400\">保密": "                            class=\"text-sm text-neutral-500 ms-2 dark:text-neutral-400\">保密",
  "____________________________class=\"text-sm_text-neutral-500_ms-2_dark:text-neutral-400\">公开": "                            class=\"text-sm text-neutral-500 ms-2 dark:text-neutral-400\">公开",
  "_分享作品_": " 分享作品 ",
  "________________________分享作品\n": "                        分享作品\n",
  "________________________分享到小红书\n": "                        分享到小红书\n",
  "____________________________跳转社区页面\n": "                            跳转社区页面\n",
  "_作品封面_": " 作品封面 ",
  "____________________作品封面\n": "                    作品封面\n",
  "选择封面": "选择封面",
  "可选封面": "可选封面",
  "____________const_link_=_document.createelement(\"a\");_//_创建a标签\n": "            const link = document.createElement(\"a\"); // 创建a标签\n",
  "____________//_link.download_=_\"pic.zip\";_//_重命名文件\n": "            // link.download = \"pic.zip\"; // 重命名文件\n",
  "____________url.revokeobjecturl(url);_//_释放内存\n": "            URL.revokeObjectURL(url); // 释放内存\n",
  "____________console.error('下载的文件出错',_e)\n": "            console.error('下载的文件出错', e)\n",
  "____________//_刷新列表\n": "            // 刷新列表\n",
  "____//_复制分享链接，写入剪贴板\n": "    // 复制分享链接，写入剪贴板\n",
  "____show_toast_duration('分享链接已复制！',_3000)\n": "    show_toast_duration('分享链接已复制！', 3000)\n",
  "________show_toast_duration('请先生成成片！',_3000)\n": "        show_toast_duration('请先生成成片！', 3000)\n",
  "____________type:_'video',_//_必填，笔记类型_'video'_|_'normal'\n": "            type: 'video', // 必填，笔记类型 'video' | 'normal'\n",
  "____________title:_'filmaction.ai电影作品：'_+_current_film.idea,_//_笔记标题\n": "            title: 'FilmAction.AI电影作品：' + current_film.idea, // 笔记标题\n",
  "____________content:_current_film.story_+_'\\n'_+_\"#filmaction_#ai电影_#pika_#runway_#midjourney_#sora\",_//_笔记正文\n": "            content: current_film.story + '\\n' + \"#FilmAction #AI电影 #pika #runway #midjourney #Sora\", // 笔记正文\n",
  "____________images:_[],_//图文类型必填，笔记图片，必须是服务器地址，暂时不支持本地文件\n": "            images: [], //图文类型必填，笔记图片，必须是服务器地址，暂时不支持本地文件\n",
  "____________video:_s3_movie_path_+_current_film.movie,_//_视频类型必填，必须是服务器地址\n": "            video: s3_movie_path + current_film.movie, // 视频类型必填，必须是服务器地址\n",
  "____________cover:_s3_scene_path_+_current_film.cover_img_//_视频封面图，必须是服务器地址，暂时不支持本地文件\n": "            cover: s3_scene_path + current_film.cover_img // 视频封面图，必须是服务器地址，暂时不支持本地文件\n",
  "____________appkey:_xhs_signature.appkey,_//必填，应用的唯一标识,\n": "            appKey: xhs_signature.appKey, //必填，应用的唯一标识,\n",
  "____________nonce:_xhs_signature.nonce,_//_必填，服务端生成签名的随机字符串\n": "            nonce: xhs_signature.nonce, // 必填，服务端生成签名的随机字符串\n",
  "____________timestamp:_xhs_signature.timestamp,_//_必填，服务端生成签名的时间戳\n": "            timestamp: xhs_signature.timestamp, // 必填，服务端生成签名的时间戳\n",
  "____________signature:_xhs_signature.signature,_//_必填，服务端生成的签名\n": "            signature: xhs_signature.signature, // 必填，服务端生成的签名\n",
  "____________//_调用失败时执行的回调函数\n": "            // 调用失败时执行的回调函数\n",
  "____________________filmaction_电影机实现您的奇思妙想\n": "                    FilmAction 电影机实现您的奇思妙想\n",
  "____________________placeholder=\"电影名\"_v-model=\"current_film.idea\">\n": "                    placeholder=\"电影名\" v-model=\"current_film.idea\">\n",
  "____________________________创建电影\n": "                            创建电影\n",
  "消耗_{{_credittype.filmcredit_}}_电影币": "消耗 {{ CreditType.FilmCredit }} 电影币",
  "_案例_": " 案例 ",
  "____________________🤗_大家都在试：\n": "                    🤗 大家都在试：\n",
  "____document.title_=_'电影创作';\n": "    document.title = '电影创作';\n",
  "_表头_": " 表头 ",
  "_一键生成脚本_": " 一键生成脚本 ",
  "_电影风格_": " 电影风格 ",
  "_一键生成分镜_": " 一键生成分镜 ",
  "_一键生成视频_": " 一键生成视频 ",
  "_一键生成旁白_": " 一键生成旁白 ",
  "_表身_": " 表身 ",
  "插入分镜": "插入分镜",
  "复制分镜": "复制分镜",
  "删除分镜": "删除分镜",
  "_选择角色_modal_": " 选择角色 modal ",
  "____<n-modal_v-model:show=\"character_modal_visibility\"_title=\"选择角色\"_preset=\"card\"\n": "    <n-modal v-model:show=\"character_modal_visibility\" title=\"选择角色\" preset=\"card\"\n",
  "____________________________脚本\n": "                            脚本\n",
  "____________________________角色\n": "                            角色\n",
  "________________________________________________空镜\n": "                                                空镜\n",
  "____________________________________________您选择了：{{_current_film.scene_character_list[index]_===\n": "                                            您选择了：{{ current_film.scene_character_list[index] ===\n",
  "________________________________________________-1_?_\"空镜\"_:_\"角色_\"_+\n": "                                                -1 ? \"空镜\" : \"角色 \" +\n",
  "____________________一键生成分镜\n": "                    一键生成分镜\n",
  "消耗_{{_credittype.imagecredit_*_current_film.frame_num_}}_电影币": "消耗 {{ CreditType.ImageCredit * current_film.frame_num }} 电影币",
  "_图片_->_视频_": " 图片 -> 视频 ",
  "_全部设置_": " 全部设置 ",
  "_全部设置": " 全部设置",
  "_选择生成模式_": " 选择生成模式 ",
  "____________________________视频动态*\n": "                            视频动态*\n",
  "_建议：人物或动物特写、中景选择“稳定”或“平衡”模式；景物或人物远景选择“默认”或“动态”模式。_": " 建议：人物或动物特写、中景选择“稳定”或“平衡”模式；景物或人物远景选择“默认”或“动态”模式。 ",
  "_时长_": " 时长 ",
  "_目标时长": " 目标时长",
  "________________________{{_current_film.duration_list[0]_}}_秒\n": "                        {{ current_film.duration_list[0] }} 秒\n",
  "_分辨率_": " 分辨率 ",
  "_目标规格": " 目标规格",
  "_消耗电影币_": " 消耗电影币 ",
  "________________________________总电影币*\n": "                                总电影币*\n",
  "规格": "规格",
  "分辨率/px": "分辨率/px",
  "电影币/次": "电影币/次",
  "_视频动态": " 视频动态",
  "____________________________________{{_current_film.duration_list[index]_}}_秒\n": "                                    {{ current_film.duration_list[index] }} 秒\n",
  "_目标分辨率": " 目标分辨率",
  "_电影币_": " 电影币 ",
  "_消耗电影币": " 消耗电影币",
  "________________________生成视频\n": "                        生成视频\n",
  "消耗_{{_video_credits.reduce((a,_b)_=>_a_+_b,_0)_}}_电影币": "消耗 {{ video_credits.reduce((a, b) => a + b, 0) }} 电影币",
  "________show_toast_duration(\"请先完成脚本！\",_3000)\n": "        show_toast_duration(\"请先完成脚本！\", 3000)\n",
  "//_生成视频\n": "// 生成视频\n",
  "____{_\"label\":_\"稳定\",_value:_\"stable\"_},\n": "    { \"label\": \"稳定\", value: \"stable\" },\n",
  "____{_\"label\":_\"平衡\",_value:_\"balanced\"_},\n": "    { \"label\": \"平衡\", value: \"balanced\" },\n",
  "____{_\"label\":_\"默认\",_value:_\"default\"_},\n": "    { \"label\": \"默认\", value: \"default\" },\n",
  "____{_\"label\":_\"动态\",_value:_\"dynamic\"_}\n": "    { \"label\": \"动态\", value: \"dynamic\" }\n",
  "________show_toast_duration(\"请先完成分镜图！\",_3000)\n": "        show_toast_duration(\"请先完成分镜图！\", 3000)\n",
  "//_无限分镜\n": "// 无限分镜\n",
  "//_操作_1：增加\n": "// 操作 1：增加\n",
  "//_操作_2：删除\n": "// 操作 2：删除\n",
  "________show_toast_duration(\"至少需要_4_个分镜！\",_3000)\n": "        show_toast_duration(\"至少需要 4 个分镜！\", 3000)\n",
  "//_操作_3：复制\n": "// 操作 3：复制\n",
  "//_操作_4：移动\n": "// 操作 4：移动\n",
  "________//_交换\n": "        // 交换\n",
  "重新合成": "重新合成",
  "合成成片": "合成成片",
  "_上传影片_": " 上传影片 ",
  "上传": "上传",
  "________________下载成片\n": "                下载成片\n",
  "________________上传成片\n": "                上传成片\n",
  "_上传影片_file_": " 上传影片 file ",
  "________const_maxsize_=_30_*_1024_*_1024;_//_20mb,测试使用更小值看效果\n": "        const maxSize = 30 * 1024 * 1024; // 20MB,测试使用更小值看效果\n",
  "____________show_toast_duration(\"请选择视频文件！\",_3000)\n": "            show_toast_duration(\"请选择视频文件！\", 3000)\n",
  "____________//_文件大小超过限制\n": "            // 文件大小超过限制\n",
  "____________show_toast_duration(\"文件大小超过限制，请选择小于30mb的文件。\",_3000)\n": "            show_toast_duration(\"文件大小超过限制，请选择小于30MB的文件。\", 3000)\n",
  "________//_传到后端\n": "        // 传到后端\n",
  "_风格_modal_": " 风格 modal ",
  "____<n-modal_v-model:show=\"style_modal_visibility\"_title=\"电影风格\"_preset=\"card\"\n": "    <n-modal v-model:show=\"style_modal_visibility\" title=\"电影风格\" preset=\"card\"\n",
  "____________分镜数过多，请自行配乐！\n": "            分镜数过多，请自行配乐！\n",
  "________________________placeholder=\"配乐描述\"_:class=\"{_'opacity-0':_current_film.music_description_zh_==_'pending'_}\"\n": "                        placeholder=\"配乐描述\" :class=\"{ 'opacity-0': current_film.music_description_zh == 'pending' }\"\n",
  "_ai_生成配乐描述\n": " AI 生成配乐描述\n",
  "_重新生成": " 重新生成",
  "消耗_{{_credittype.musiccredit_}}_电影币": "消耗 {{ CreditType.MusicCredit }} 电影币",
  "生成配乐": "生成配乐",
  "________________________更多\n": "                        更多\n",
  "_重新生成_": " 重新生成 ",
  "消耗_{{_credittype.imagecredit_}}_电影币": "消耗 {{ CreditType.ImageCredit }} 电影币",
  "_上传分镜_": " 上传分镜 ",
  "_全屏_": " 全屏 ",
  "_放大分镜_": " 放大分镜 ",
  "_下载_": " 下载 ",
  "_下载分镜_": " 下载分镜 ",
  "_生成分镜图片_": " 生成分镜图片 ",
  "生成分镜": "生成分镜",
  "_全屏查看图片_modal_": " 全屏查看图片 modal ",
  "_选择角色modal_": " 选择角色modal ",
  "________<n-modal_v-model:show=\"character_modal_visibility\"_title=\"选择角色\"_preset=\"card\"\n": "        <n-modal v-model:show=\"character_modal_visibility\" title=\"选择角色\" preset=\"card\"\n",
  "________________________________脚本\n": "                                脚本\n",
  "________________________________角色\n": "                                角色\n",
  "____________________________________________________空镜\n": "                                                    空镜\n",
  "________________________________________________您选择了：{{_current_film.scene_character_list[index]_===\n": "                                                您选择了：{{ current_film.scene_character_list[index] ===\n",
  "____________________________________________________-1_?_\"空镜\"_:_\"角色_\"_+\n": "                                                    -1 ? \"空镜\" : \"角色 \" +\n",
  "生成分镜图片_": "生成分镜图片 ",
  "_上传分镜_file_": " 上传分镜 file ",
  "____________show_toast_duration(\"请选择图片文件！\",_3000)\n": "            show_toast_duration(\"请选择图片文件！\", 3000)\n",
  "________const_maxsize_=_10_*_1024_*_1024;_//_设置文件最大值为_10mb\n": "        const maxSize = 10 * 1024 * 1024; // 设置文件最大值为 10MB\n",
  "____________show_toast_duration(\"文件大小超过限制，请选择小于_10mb_的文件。\",_3000)\n": "            show_toast_duration(\"文件大小超过限制，请选择小于 10MB 的文件。\", 3000)\n",
  "____________placeholder=\"分镜脚本\"_:class=\"{_'opacity-0':_current_film.script_list[props.index]_==_'pending'_}\"\n": "            placeholder=\"分镜脚本\" :class=\"{ 'opacity-0': current_film.script_list[props.index] == 'pending' }\"\n",
  "________________placeholder=\"旁白\"\n": "                placeholder=\"旁白\"\n",
  "_剧本_": " 剧本 ",
  "________________placeholder=\"填写您的故事或让_ai_生成~\"_:class=\"{_'opacity-0':_current_film.story_==_'pending'_}\"\n": "                placeholder=\"填写您的故事或让 AI 生成~\" :class=\"{ 'opacity-0': current_film.story == 'pending' }\"\n",
  "_类型_": " 类型 ",
  "________________________ai_生成故事大纲\n": "                        AI 生成故事大纲\n",
  "________________________重新生成故事大纲\n": "                        重新生成故事大纲\n",
  "_生成失败_": " 生成失败 ",
  "生成失败，请重试": "生成失败，请重试",
  "_如果已经生成了优化视频，则显示优化视频_": " 如果已经生成了优化视频，则显示优化视频 ",
  "_否则显示原始视频_": " 否则显示原始视频 ",
  "_ai_优化_": " AI 优化 ",
  "_ai_优化": " AI 优化",
  "_下载视频_": " 下载视频 ",
  "生成视频": "生成视频",
  "_初次从分镜_->_视频_": " 初次从分镜 -> 视频 ",
  "____________________________{{_current_film.duration_list[index]_}}_秒\n": "                            {{ current_film.duration_list[index] }} 秒\n",
  "____________________生成视频\n": "                    生成视频\n",
  "____//_只剩_2_个\n": "    // 只剩 2 个\n",
  "________show_toast_duration(\"至少保留_2_帧！\",_3000)\n": "        show_toast_duration(\"至少保留 2 帧！\", 3000)\n",
  "____//_最后一个\n": "    // 最后一个\n",
  "const_formattooltip_=_(value:_number)_=>_`${value}秒`\n": "const formatTooltip = (value: number) => `${value}秒`\n",
  "________show_toast_duration(\"请先生成分镜图！\",_3000);\n": "        show_toast_duration(\"请先生成分镜图！\", 3000);\n",
  "_一键设置所有声音_": " 一键设置所有声音 ",
  "____________设置所有声音\n": "            设置所有声音\n",
  "____________________选择声音\n": "                    选择声音\n",
  "____<n-modal_v-model:show=\"showmodal\"_:title=\"index_==_-1_?_'全部声音设置'_:_'选择声音'\"_preset=\"card\"\n": "    <n-modal v-model:show=\"showModal\" :title=\"index == -1 ? '全部声音设置' : '选择声音'\" preset=\"card\"\n",
  "____//_设置所有声音\n": "    // 设置所有声音\n",
  "____//_某个旁白\n": "    // 某个旁白\n",
  "____//_其他都暂停\n": "    // 其他都暂停\n",
  "________________placeholder=\"图片创意\"_v-model=\"current_image.idea\"_rows='4'>": "                placeholder=\"图片创意\" v-model=\"current_image.idea\" rows='4'>",
  "____________________{{_current_image.aspect_ratio_==_\"\"_?_\"图片比例\"_:_current_image.aspect_ratio_}}\n": "                    {{ current_image.aspect_ratio == \"\" ? \"图片比例\" : current_image.aspect_ratio }}\n",
  "_生成图片\n": " 生成图片\n",
  "____________________生成失败，请更换提示词重试！\n": "                    生成失败，请更换提示词重试！\n",
  "重新生成": "重新生成",
  "____________下载\n": "            下载\n",
  "________document.title_=_'图片生成';\n": "        document.title = '图片生成';\n",
  "____________加载更多\n": "            加载更多\n",
  "____________________rows=\"4\"_placeholder=\"音乐创意\"_v-model=\"current_music.idea\">": "                    rows=\"4\" placeholder=\"音乐创意\" v-model=\"current_music.idea\">",
  "____________________________音乐时长\n": "                            音乐时长\n",
  "____________________________}}_秒": "                            }} 秒",
  "_生成音乐\n": " 生成音乐\n",
  "________________下载\n": "                下载\n",
  "________document.title_=_'音乐生成';\n": "        document.title = '音乐生成';\n",
  "____<n-modal_v-model:show=\"delete_modal_visibility\"_title=\"删除音乐\"_preset=\"card\"\n": "    <n-modal v-model:show=\"delete_modal_visibility\" title=\"删除音乐\" preset=\"card\"\n",
  "_上传图片\n": " 上传图片\n",
  "_上传音频\n": " 上传音频\n",
  "_生成视频\n": " 生成视频\n",
  "消耗_{{_credittype.phototalkcredit_}}_电影币": "消耗 {{ CreditType.PhotoTalkCredit }} 电影币",
  "生成结果": "生成结果",
  "_重新生成\n": " 重新生成\n",
  "_下载\n": " 下载\n",
  "________document.title_=_'图片说话';\n": "        document.title = '图片说话';\n",
  "________________show_toast_duration(\"请选择图片文件！\",_3000);\n": "                show_toast_duration(\"请选择图片文件！\", 3000);\n",
  "________________show_toast_duration(\"图片大小超过_5_mb，上传失败！\",_3000);\n": "                show_toast_duration(\"图片大小超过 5 MB，上传失败！\", 3000);\n",
  "________________show_toast_duration(\"请选择音频文件！\",_3000);\n": "                show_toast_duration(\"请选择音频文件！\", 3000);\n",
  "________________show_toast_duration(\"音频大小超过_5_mb，上传失败！\",_3000);\n": "                show_toast_duration(\"音频大小超过 5 MB，上传失败！\", 3000);\n",
  "____//_新生成\n": "    // 新生成\n",
  "____________show_toast_duration(\"请上传图片！\",_3000);\n": "            show_toast_duration(\"请上传图片！\", 3000);\n",
  "____________show_toast_duration(\"请上传音频！\",_3000);\n": "            show_toast_duration(\"请上传音频！\", 3000);\n",
  "____//_重新生成\n": "    // 重新生成\n",
  "_加载更多\n": " 加载更多\n",
  "_确认删除\n": " 确认删除\n",
  "_视频模板_": " 视频模板 ",
  "____________________________________@click=\"current_trending.template_id_=_video.id;_trending_video_template_modal_visibility_=_false\">选择模板": "                                    @click=\"current_trending.template_id = video.id; trending_video_template_modal_visibility = false\">选择模板",
  "_生成_": " 生成 ",
  "_选中的视频模板_": " 选中的视频模板 ",
  "_删除模板小叉_": " 删除模板小叉 ",
  "________________________________选择爆款模板\n": "                                选择爆款模板\n",
  "_删除图片小叉_": " 删除图片小叉 ",
  "_上传图片_": " 上传图片 ",
  "________________________________上传图片\n": "                                上传图片\n",
  "________________________一键生成\n": "                        一键生成\n",
  "消耗_{{_credittype.trendingvideocredit_}}_电影币": "消耗 {{ CreditType.TrendingVideoCredit }} 电影币",
  "________________视频生成中\n": "                视频生成中\n",
  "_生成结果_": " 生成结果 ",
  "____document.title_=_'爆款视频';\n": "    document.title = '爆款视频';\n",
  "________alert('请选择视频模板');\n": "        alert('请选择视频模板');\n",
  "________alert('请上传图片');\n": "        alert('请上传图片');\n",
  "_上传生成_": " 上传生成 ",
  "_input_隐藏_": " input 隐藏 ",
  "_上传图片按钮_": " 上传图片按钮 ",
  "____________________批量上传图片\n": "                    批量上传图片\n",
  "*_每次最多上传_20_张": "* 每次最多上传 20 张",
  "*_请上传长宽比为_16:9_的图片": "* 请上传长宽比为 16:9 的图片",
  "_展示上传的图_": " 展示上传的图 ",
  "____________________________________视频动态*\n": "                                    视频动态*\n",
  "________________________________{{_video_durations[0]_}}_秒\n": "                                {{ video_durations[0] }} 秒\n",
  "________________________________________总电影币*\n": "                                        总电影币*\n",
  "_上传的图片_": " 上传的图片 ",
  "_移除_": " 移除 ",
  "________________________________________________{{_video_durations[index]_}}_秒\n": "                                                {{ video_durations[index] }} 秒\n",
  "________________________________生成视频\n": "                                生成视频\n",
  "_生成好的_": " 生成好的 ",
  "____________________________生成失败，请重试！\n": "                            生成失败，请重试！\n",
  "________________________________class=\"mt-2_text-indigo-600_hover:text-indigo-800\">_下载图片": "                                class=\"mt-2 text-indigo-600 hover:text-indigo-800\"> 下载图片",
  "_优化视频_": " 优化视频 ",
  "_基础视频_": " 基础视频 ",
  "____________________________________更多\n": "                                    更多\n",
  "____________________________________下载视频\n": "                                    下载视频\n",
  "_删除_": " 删除 ",
  "____________________________________删除\n": "                                    删除\n",
  "//_展示视频\n": "// 展示视频\n",
  "____document.title_=_'filmaction_|_视频生成';\n": "    document.title = 'FilmAction | 视频生成';\n",
  "____________________show_toast_duration(\"请选择图片文件！\",_3000);\n": "                    show_toast_duration(\"请选择图片文件！\", 3000);\n",
  "________________const_maxsize_=_10_*_1024_*_1024;_//_设置文件最大值为_10mb\n": "                const maxSize = 10 * 1024 * 1024; // 设置文件最大值为 10MB\n",
  "____________________//_文件大小超过限制\n": "                    // 文件大小超过限制\n",
  "____________________show_toast_duration(\"文件大小超过限制，请选择小于_10mb_的文件。\",_3000)\n": "                    show_toast_duration(\"文件大小超过限制，请选择小于 10MB 的文件。\", 3000)\n",
  "____________________show_toast_duration(\"上传的图片数量过多，选取前_20_张！\",_3000);\n": "                    show_toast_duration(\"上传的图片数量过多，选取前 20 张！\", 3000);\n",
  "________________//_添加到数组\n": "                // 添加到数组\n",
  "____________//_打开设置动态面板\n": "            // 打开设置动态面板\n",
  "____//_提交完成\n": "    // 提交完成\n",
  "____//_重新获取视频列表\n": "    // 重新获取视频列表\n",
  "____________________使用\n": "                    使用\n",
  "____________________制作\n": "                    制作\n",
  "________________________电影类型\n": "                        电影类型\n",
  "_风格_": " 风格 ",
  "________________________电影风格\n": "                        电影风格\n",
  "_主角_": " 主角 ",
  "________________________主角描述\n": "                        主角描述\n",
  "________________________故事大纲\n": "                        故事大纲\n",
  "_分镜_": " 分镜 ",
  "________________想要继续生成视频？快来试试_👇_吧！\n": "                想要继续生成视频？快来试试 👇 吧！\n",
  "____________________下载故事板\n": "                    下载故事板\n",
  "________________________再来一个\n": "                        再来一个\n",
  "________allowtaint:_true,_//开启跨域\n": "        allowTaint: true, //开启跨域\n",
  "____________________创建电影\n": "                    创建电影\n",
  "const_idea_hint_=_ref(\"主角穿越时空\")\n": "const idea_hint = ref(\"主角穿越时空\")\n",
  "____//_更新电影点子\n": "    // 更新电影点子\n",
  "更改密码": "更改密码",
  "____________________________邮箱\n": "                            邮箱\n",
  "{{_countdown_}}_秒后重试\n": "{{ countdown }} 秒后重试\n",
  "获取验证码": "获取验证码",
  "____________________________验证码\n": "                            验证码\n",
  "________________________________新密码\n": "                                新密码\n",
  "________________________________确认密码\n": "                                确认密码\n",
  "________________________@click=\"change_password\">重置密码": "                        @click=\"change_password\">重置密码",
  "________show_toast_duration('密码两次输入不一致！',_3000)\n": "        show_toast_duration('密码两次输入不一致！', 3000)\n",
  "____________用户反馈\n": "            用户反馈\n",
  "________________创意天才们的体验如何，您的全能电影机是否成功帮助您落实创意？您的反馈让_filmaction_全能电影机变得更好！更棒的体验、更多的可能，从您的留言开始～\n": "                创意天才们的体验如何，您的全能电影机是否成功帮助您落实创意？您的反馈让 FilmAction 全能电影机变得更好！更棒的体验、更多的可能，从您的留言开始～\n",
  "您在\n": "您在\n",
  "________________filmaction_使用了哪些": "                FilmAction 使用了哪些",
  "电影风格": "电影风格",
  "_电影类型_": " 电影类型 ",
  "电影类型": "电影类型",
  "_成片风格评分_": " 成片风格评分 ",
  "成片风格_": "成片风格 ",
  "是否与您预期一致？\n": "是否与您预期一致？\n",
  "_成片类型评分_": " 成片类型评分 ",
  "_成片类型_": " 成片类型 ",
  "_故事大纲评分_": " 故事大纲评分 ",
  "________________class=\"block_mb-2_text-sm_font-medium_dark:text-white\">您是否满意\n": "                class=\"block mb-2 text-sm font-medium dark:text-white\">您是否满意\n",
  "________________filmaction_的": "                FilmAction 的",
  "故事大纲": "故事大纲",
  "_分镜评分_": " 分镜评分 ",
  "分镜图片": "分镜图片",
  "_视频评分_": " 视频评分 ",
  "视频片段": "视频片段",
  "_配乐评分_": " 配乐评分 ",
  "配乐": "配乐",
  "_功能评价_": " 功能评价 ",
  "________________class=\"block_mb-2_text-sm_font-medium_dark:text-white\">以上功能使用中您遇到的<span\n": "                class=\"block mb-2 text-sm font-medium dark:text-white\">以上功能使用中您遇到的<span\n",
  "____________________class=\"text-indigo-600_dark:text-indigo-200\">具体的问题、不满意的地方": "                    class=\"text-indigo-600 dark:text-indigo-200\">具体的问题、不满意的地方",
  "____________________placeholder=\"越具体，就越聚焦，期待调整后的电影机更懂您心意\"_v-model=\"feedback_form.feedback\">": "                    placeholder=\"越具体，就越聚焦，期待调整后的电影机更懂您心意\" v-model=\"feedback_form.feedback\">",
  "_易用性评分_": " 易用性评分 ",
  "________________class=\"block_mb-2_text-sm_font-medium_dark:text-white\">您是否能够<span\n": "                class=\"block mb-2 text-sm font-medium dark:text-white\">您是否能够<span\n",
  "____________________class=\"text-indigo-600_dark:text-indigo-200\">很快上手": "                    class=\"text-indigo-600 dark:text-indigo-200\">很快上手",
  "_推荐评分_": " 推荐评分 ",
  "________________class=\"block_mb-2_text-sm_font-medium_dark:text-white\">您是否愿意把\n": "                class=\"block mb-2 text-sm font-medium dark:text-white\">您是否愿意把\n",
  "推荐给您的朋友": "推荐给您的朋友",
  "_建议_": " 建议 ",
  "您对\n": "您对\n",
  "建议": "建议",
  "____________________placeholder=\"您的反馈将带来与_filmaction_更好的相见\"_v-model=\"feedback_form.suggestion\">": "                    placeholder=\"您的反馈将带来与 FilmAction 更好的相见\" v-model=\"feedback_form.suggestion\">",
  "_联系方式_": " 联系方式 ",
  "________________留下您的": "                留下您的",
  "联系方式": "联系方式",
  "，让工作人员更好地联系您（选填）\n": "，让工作人员更好地联系您（选填）\n",
  "____________________placeholder=\"聚焦您的创作体验，塑造服务您创意开发的全能电影机\"_v-model=\"feedback_form.contact\">": "                    placeholder=\"聚焦您的创作体验，塑造服务您创意开发的全能电影机\" v-model=\"feedback_form.contact\">",
  "_提交_": " 提交 ",
  "________________@click=\"send_feedback\">提交": "                @click=\"send_feedback\">提交",
  "____1:_'很差',\n": "    1: '很差',\n",
  "____2:_'较差',\n": "    2: '较差',\n",
  "____3:_'一般',\n": "    3: '一般',\n",
  "____4:_'好',\n": "    4: '好',\n",
  "____5:_'很好'\n": "    5: '很好'\n",
  "________show_toast_duration('请选择电影类型！',_3000)\n": "        show_toast_duration('请选择电影类型！', 3000)\n",
  "________show_toast_duration('请选择电影风格！',_3000)\n": "        show_toast_duration('请选择电影风格！', 3000)\n",
  "________show_toast_duration('请选择成片风格评分！',_3000)\n": "        show_toast_duration('请选择成片风格评分！', 3000)\n",
  "________show_toast_duration('请选择成片类型评分！',_3000)\n": "        show_toast_duration('请选择成片类型评分！', 3000)\n",
  "________show_toast_duration('请选择故事大纲评分！',_3000)\n": "        show_toast_duration('请选择故事大纲评分！', 3000)\n",
  "________show_toast_duration('请选择分镜评分！',_3000)\n": "        show_toast_duration('请选择分镜评分！', 3000)\n",
  "________show_toast_duration('请选择视频评分！',_3000)\n": "        show_toast_duration('请选择视频评分！', 3000)\n",
  "________show_toast_duration('请选择配乐评分！',_3000)\n": "        show_toast_duration('请选择配乐评分！', 3000)\n",
  "________show_toast_duration('请选择易用性评分！',_3000)\n": "        show_toast_duration('请选择易用性评分！', 3000)\n",
  "________show_toast_duration('请选择推荐评分！',_3000)\n": "        show_toast_duration('请选择推荐评分！', 3000)\n",
  "________show_toast_duration('请填写功能评价！',_3000)\n": "        show_toast_duration('请填写功能评价！', 3000)\n",
  "________show_toast_duration('请填写建议！',_3000)\n": "        show_toast_duration('请填写建议！', 3000)\n",
  "____________账户设置\n": "            账户设置\n",
  "________________________头像\n": "                        头像\n",
  "________________________________更换头像\n": "                                更换头像\n",
  "________________________用户名\n": "                        用户名\n",
  "____________________________v-model=\"account.account.username\"_placeholder=\"怎样在创意乐园里称呼您？\">\n": "                            v-model=\"account.account.username\" placeholder=\"怎样在创意乐园里称呼您？\">\n",
  "________________________邮箱\n": "                        邮箱\n",
  "________________________placeholder=\"邮箱（登录账号已绑定邮箱）\"_v-model=\"account.account.email\"_readonly>\n": "                        placeholder=\"邮箱（登录账号已绑定邮箱）\" v-model=\"account.account.email\" readonly>\n",
  "________________________密码\n": "                        密码\n",
  "____________________________更改密码\n": "                            更改密码\n",
  "________________________电话号码\n": "                        电话号码\n",
  "暂不透露\n": "暂不透露\n",
  "____________________________:disabled=\"hide_phone\">允许官方联系我": "                            :disabled=\"hide_phone\">允许官方联系我",
  "________________________placeholder=\"电话号码\"_v-model=\"account.account.phone\"_v-if=\"!hide_phone\">\n": "                        placeholder=\"电话号码\" v-model=\"account.account.phone\" v-if=\"!hide_phone\">\n",
  "________________________社媒账号\n": "                        社媒账号\n",
  "________________________placeholder=\"展现您的个人符号，让大家快速认识您。\"_v-model=\"account.account.media\"_v-if=\"!hide_media\">\n": "                        placeholder=\"展现您的个人符号，让大家快速认识您。\" v-model=\"account.account.media\" v-if=\"!hide_media\">\n",
  "保密\n": "保密\n",
  "________________________个人简介\n": "                        个人简介\n",
  "________________________rows=\"6\"_placeholder=\"灵感的碰撞带来创意的惊喜，完善个人简介，让不同的灵魂更好地认识您~\"\n": "                        rows=\"6\" placeholder=\"灵感的碰撞带来创意的惊喜，完善个人简介，让不同的灵魂更好地认识您~\"\n",
  "________________________您的职业\n": "                        您的职业\n",
  "________________________placeholder=\"请输入\"_v-model=\"job_name\"_v-else>\n": "                        placeholder=\"请输入\" v-model=\"job_name\" v-else>\n",
  "________________________使用场景\n": "                        使用场景\n",
  "________________________________placeholder=\"请输入\"_v-model=\"reasons_input_value[i].value\">\n": "                                placeholder=\"请输入\" v-model=\"reasons_input_value[i].value\">\n",
  "____________________________注销用户\n": "                            注销用户\n",
  "________________________<n-modal_v-model:show=\"delete_user_modal_visibility\"_title=\"注销用户\"_preset=\"card\"\n": "                        <n-modal v-model:show=\"delete_user_modal_visibility\" title=\"注销用户\" preset=\"card\"\n",
  "账号中的虚拟财产、积分以及所有其他站内权益将被清零，自愿放弃未使用的全部上述权益；\n": "账号中的虚拟财产、积分以及所有其他站内权益将被清零，自愿放弃未使用的全部上述权益；\n",
  "除法定需保留的信息以外，包括生成历史及相关内容等账号信息将被不可复原地全部删除。因未及时保存而可能造成损失均由用户本人承担；": "除法定需保留的信息以外，包括生成历史及相关内容等账号信息将被不可复原地全部删除。因未及时保存而可能造成损失均由用户本人承担；",
  "账号注销后，用户与瀚皓之间各类关系已全部结清，不存在任何未了之争议。": "账号注销后，用户与瀚皓之间各类关系已全部结清，不存在任何未了之争议。",
  "________________________________________我已阅读、理解并同意上述内容\n": "                                        我已阅读、理解并同意上述内容\n",
  "____________________________________确认注销\n": "                                    确认注销\n",
  "____________________________更新\n": "                            更新\n",
  "____{_\"reason\":_\"工作项目需要\",_\"type\":_[\"特效制作\",_\"广告宣传\",_\"预设项目_demo\",_\"为影视作品制作提供更多场景画面\",_\"项目要求依靠_ai_工具制作内容\",_\"其他\"]_},\n": "    { \"reason\": \"工作项目需要\", \"type\": [\"特效制作\", \"广告宣传\", \"预设项目 Demo\", \"为影视作品制作提供更多场景画面\", \"项目要求依靠 AI 工具制作内容\", \"其他\"] },\n",
  "____{_\"reason\":_\"学校需要\",_\"type\":_[\"学校课程要求\",_\"课程作业辅助\",_\"创意比赛\",_\"其他\"]_},\n": "    { \"reason\": \"学校需要\", \"type\": [\"学校课程要求\", \"课程作业辅助\", \"创意比赛\", \"其他\"] },\n",
  "____{_\"reason\":_\"个人需要\",_\"type\":_[\"辅助进行在内容平台的内容创作（同人内容、二创等）\",_\"辅助制作_vlog_等视频后期内容（开头、转场、特效）\",_\"找到灵感启发\",_\"对_ai_技术与工具感兴趣，并希望掌握使用_ai_工具的技能\",_\"兴趣爱好\",_\"其他\"]_},\n": "    { \"reason\": \"个人需要\", \"type\": [\"辅助进行在内容平台的内容创作（同人内容、二创等）\", \"辅助制作 Vlog 等视频后期内容（开头、转场、特效）\", \"找到灵感启发\", \"对 AI 技术与工具感兴趣，并希望掌握使用 AI 工具的技能\", \"兴趣爱好\", \"其他\"] },\n",
  "____{_\"reason\":_\"其他\",_\"type\":_[\"其他\"]_}\n": "    { \"reason\": \"其他\", \"type\": [\"其他\"] }\n",
  "____if_(reasons_select[i]_==_\"\"_||_reasons_select[i]_==_\"其他\")_{\n": "    if (reasons_select[i] == \"\" || reasons_select[i] == \"其他\") {\n",
  "const_job_styles_=_ref([\"影视行业从业者\",_\"内容平台创作者\",_\"创意策划行业从业者\",_\"高校学生\",_\"其他\"])\n": "const job_styles = ref([\"影视行业从业者\", \"内容平台创作者\", \"创意策划行业从业者\", \"高校学生\", \"其他\"])\n",
  "________case_\"影视行业从业者\":\n": "        case \"影视行业从业者\":\n",
  "____________return_[\"导演\",_\"制片\",_\"编剧\",_\"摄像\",_\"后期\",_\"宣发\",_\"影视项目策划\",_\"影视公司/工作室主理人\",_\"其他\"]\n": "            return [\"导演\", \"制片\", \"编剧\", \"摄像\", \"后期\", \"宣发\", \"影视项目策划\", \"影视公司/工作室主理人\", \"其他\"]\n",
  "________case_\"内容平台创作者\":\n": "        case \"内容平台创作者\":\n",
  "____________return_[\"媒体\",_\"公关\",_\"自媒体博主\",_\"文学创作者\",_\"其他\"]\n": "            return [\"媒体\", \"公关\", \"自媒体博主\", \"文学创作者\", \"其他\"]\n",
  "________case_\"创意策划行业从业者\":\n": "        case \"创意策划行业从业者\":\n",
  "____________return_[\"游戏公司从业者\",_\"美工设计\",_\"广告策划者\",_\"营销策划者\",_\"内容平台主理人\",_\"其他\"]\n": "            return [\"游戏公司从业者\", \"美工设计\", \"广告策划者\", \"营销策划者\", \"内容平台主理人\", \"其他\"]\n",
  "________case_\"高校学生\":\n": "        case \"高校学生\":\n",
  "____________return_[\"影视制作相关专业（导演、摄影、制片、后期等）\",_\"设计相关专业（视觉设计、数字艺术等）\",_\"艺术管理相关专业（文化产业管理、策展等）\",_\"中文/文学专业\",_\"计算机专业\",_\"其他\"]\n": "            return [\"影视制作相关专业（导演、摄影、制片、后期等）\", \"设计相关专业（视觉设计、数字艺术等）\", \"艺术管理相关专业（文化产业管理、策展等）\", \"中文/文学专业\", \"计算机专业\", \"其他\"]\n",
  "________case_\"其他\":\n": "        case \"其他\":\n",
  "____if_(account.account.job_type_==_\"其他\"_||_account.account.job_style_==_\"其他\")_{\n": "    if (account.account.job_type == \"其他\" || account.account.job_style == \"其他\") {\n",
  "____if_(account.account.job_style_!==_'其他'_&&_account.account.job_style_!==_'')_{\n": "    if (account.account.job_style !== '其他' && account.account.job_style !== '') {\n",
  "____}_else_if_(account.account.job_style_==_'其他')_{\n": "    } else if (account.account.job_style == '其他') {\n",
  "________if_(reasons_select[i]_==_\"其他\"_||_reasons_select[i]_==_\"\")_{\n": "        if (reasons_select[i] == \"其他\" || reasons_select[i] == \"\") {\n",
  "____________reasons_select[i]_=_\"其他\";\n": "            reasons_select[i] = \"其他\";\n",
  "________show_toast_duration(\"请先阅读并同意注销用户协议！\",_3000)\n": "        show_toast_duration(\"请先阅读并同意注销用户协议！\", 3000)\n",
  "____________我喜欢的\n": "            我喜欢的\n",
  "____________以电影机跨越阻碍，以影像链接思想，看到由您定义的世界\n": "            以电影机跨越阻碍，以影像链接思想，看到由您定义的世界\n",
  "____________我的电影\n": "            我的电影\n",
  "________上传作品\n": "        上传作品\n",
  "________加载更多\n": "        加载更多\n",
  "____<n-modal_v-model:show=\"showmodal\"_title=\"上传影片\"_preset=\"card\"\n": "    <n-modal v-model:show=\"showModal\" title=\"上传影片\" preset=\"card\"\n",
  "_名称字段_": " 名称字段 ",
  "名称": "名称",
  "_影片故事简介字段_": " 影片故事简介字段 ",
  "____________________class=\"block_text-sm_font-medium_text-gray-700_dark:text-gray-300_mt-4\">影片故事简介": "                    class=\"block text-sm font-medium text-gray-700 dark:text-gray-300 mt-4\">影片故事简介",
  "_成片上传字段_": " 成片上传字段 ",
  "成片上传": "成片上传",
  "_确认上传按钮_": " 确认上传按钮 ",
  "________________________确认上传\n": "                        确认上传\n",
  "________const_maxsize_=_30_*_1024_*_1024;_//_30mb,测试使用更小值看效果\n": "        const maxSize = 30 * 1024 * 1024; // 30MB,测试使用更小值看效果\n",
  "____uploadformdata.append('movie_type',_\"剧情片\");_//_默认_剧情片\n": "    uploadFormData.append('movie_type', \"剧情片\"); // 默认 剧情片\n",
  "____uploadformdata.append('movie_style',_\"\");_//_默认空\n": "    uploadFormData.append('movie_style', \"\"); // 默认空\n",
  "________//_处理成功响应\n": "        // 处理成功响应\n",
  "________show_toast_duration(\"上传作品成功！\",_3000)\n": "        show_toast_duration(\"上传作品成功！\", 3000)\n",
  "________showmodal.value_=_false;__//_关闭模态框\n": "        showModal.value = false;  // 关闭模态框\n",
  "________//_处理错误响应\n": "        // 处理错误响应\n",
  "_背景视频_": " 背景视频 ",
  "_声音按钮_": " 声音按钮 ",
  "_进入_": " 进入 ",
  "_即刻体验\n": " 即刻体验\n",
  "_现在进入\n": " 现在进入\n",
  "_编辑推荐_": " 编辑推荐 ",
  "_封面_": " 封面 ",
  "_信息_": " 信息 ",
  "_最热榜_": " 最热榜 ",
  "________最热榜\n": "        最热榜\n",
  "_热度标签_": " 热度标签 ",
  "_最新榜_": " 最新榜 ",
  "最新榜": "最新榜",
  "京icp备2024085203号-1": "京ICP备2024085203号-1",
  "__now.setdate(now.getdate()_-_num);_//_设置为num天前的日期\n": "  now.setDate(now.getDate() - num); // 设置为num天前的日期\n",
  "__const_month_=_(now.getmonth()_+_1).tostring().padstart(2,_'0');_//_月份从0开始，需要加1并补零\n": "  const month = (now.getMonth() + 1).toString().padStart(2, '0'); // 月份从0开始，需要加1并补零\n",
  "__const_day_=_now.getdate().tostring().padstart(2,_'0');_//_补零\n": "  const day = now.getDate().toString().padStart(2, '0'); // 补零\n",
  "__const_hours_=_now.gethours().tostring().padstart(2,_'0');_//_补零\n": "  const hours = now.getHours().toString().padStart(2, '0'); // 补零\n",
  "__const_minutes_=_now.getminutes().tostring().padstart(2,_'0');_//_补零\n": "  const minutes = now.getMinutes().toString().padStart(2, '0'); // 补零\n",
  "__const_seconds_=_now.getseconds().tostring().padstart(2,_'0');_//_补零\n": "  const seconds = now.getSeconds().toString().padStart(2, '0'); // 补零\n",
  "__//_编辑推荐\n": "  // 编辑推荐\n",
  "__//_trending_movies_中排除_recommend_movies\n": "  // trending_movies 中排除 recommend_movies\n",
  "__//_latest_movies_中排除_trending_movies\n": "  // latest_movies 中排除 trending_movies\n",
  "________return_'创建电影'\n": "        return '创建电影'\n",
  "________return_'生成音乐'\n": "        return '生成音乐'\n",
  "________return_'生成图片'\n": "        return '生成图片'\n",
  "________return_'图片说话'\n": "        return '图片说话'\n",
  "________return_'爆款视频'\n": "        return '爆款视频'\n",
  "________return_'全部'\n": "        return '全部'\n",
  "_透明区域_": " 透明区域 ",
  "_主体_": " 主体 ",
  "_列表_": " 列表 ",
  "____________________________拿起您的专属电影机，让创作不受限\n": "                            拿起您的专属电影机，让创作不受限\n",
  "重置密码": "重置密码",
  "____________________________________________还记得您的密码？\n": "                                            还记得您的密码？\n",
  "____________________________________________________在此登录\n": "                                                    在此登录\n",
  "________________________________________________________邮箱\n": "                                                        邮箱\n",
  "部分邮箱可能被拦截，还请同步留意您的广告邮件\n": "部分邮箱可能被拦截，还请同步留意您的广告邮件\n",
  "________________________________________________________验证码\n": "                                                        验证码\n",
  "____________________________________________________________新密码\n": "                                                            新密码\n",
  "____________________________________________________________再次输入\n": "                                                            再次输入\n",
  "____________________________________________________@click=\"register\">重置密码": "                                                    @click=\"register\">重置密码",
  "________________show_toast_duration('请输入有效的邮箱！',_3000)\n": "                show_toast_duration('请输入有效的邮箱！', 3000)\n",
  "________________show_toast_duration('请输入有效的邮箱和密码！',_3000)\n": "                show_toast_duration('请输入有效的邮箱和密码！', 3000)\n",
  "________________show_toast_duration('密码两次输入不一致',_3000)\n": "                show_toast_duration('密码两次输入不一致', 3000)\n",
  "登录": "登录",
  "document.title_=_'登录';\n": "document.title = '登录';\n",
  "________show_toast_duration('请先阅读并同意用户协议和隐私政策！',_3000)\n": "        show_toast_duration('请先阅读并同意用户协议和隐私政策！', 3000)\n",
  "________show_toast_duration('邮箱或密码不能为空！',_3000)\n": "        show_toast_duration('邮箱或密码不能为空！', 3000)\n",
  "________show_toast_duration(\"登陆成功\",_3000)\n": "        show_toast_duration(\"登陆成功\", 3000)\n",
  "________//_管理员账户\n": "        // 管理员账户\n",
  "____________//_没填写过信息的\n": "            // 没填写过信息的\n",
  "____________//_填写过信息的\n": "            // 填写过信息的\n",
  "________//_如果是联想用户\n": "        // 如果是联想用户\n",
  "________________show_toast_duration('生成的影片已成功添加到您的作品中！',_3000)\n": "                show_toast_duration('生成的影片已成功添加到您的作品中！', 3000)\n",
  "____________show_toast_duration(\"用户名或密码错误\",_3000)\n": "            show_toast_duration(\"用户名或密码错误\", 3000)\n",
  "________________________________关注\n": "                                关注\n",
  "_浏览量显示区域_": " 浏览量显示区域 ",
  "_如果是管理员_": " 如果是管理员 ",
  "____________________________评论\n": "                            评论\n",
  "____________________________________分享\n": "                                    分享\n",
  "_分享到小红书_": " 分享到小红书 ",
  "____________________________________分享到小红书\n": "                                    分享到小红书\n",
  "_获取分享链接_": " 获取分享链接 ",
  "____________________________________获取分享链接\n": "                                    获取分享链接\n",
  "____________________________获取分享链接\n": "                            获取分享链接\n",
  "猜您喜欢": "猜您喜欢",
  "________if_(account.is_login_&&_!(account.is_admin()))_{_//_登陆了_且_不是管理员_获取对这个作品点赞情况\n": "        if (account.is_login && !(account.is_admin())) { // 登陆了 且 不是管理员 获取对这个作品点赞情况\n",
  "//获取最新作品\n": "//获取最新作品\n",
  "//_更新recommend情况\n": "// 更新recommend情况\n",
  "____________title:_'filmaction.ai电影作品：'_+_movie_data.idea,_//_笔记标题\n": "            title: 'FilmAction.AI电影作品：' + movie_data.idea, // 笔记标题\n",
  "____________content:_movie_data.story_+_'\\n'_+_\"#filmaction_#ai电影_#pika_#runway_#midjourney_#sora\",_//_笔记正文\n": "            content: movie_data.story + '\\n' + \"#FilmAction #AI电影 #pika #runway #midjourney #Sora\", // 笔记正文\n",
  "____________video:_s3_movie_path_+_movie_data.movie,_//_视频类型必填，必须是服务器地址\n": "            video: s3_movie_path + movie_data.movie, // 视频类型必填，必须是服务器地址\n",
  "____________cover:_s3_scene_path_+_movie_data.cover_img_//_视频封面图，必须是服务器地址，暂时不支持本地文件\n": "            cover: s3_scene_path + movie_data.cover_img // 视频封面图，必须是服务器地址，暂时不支持本地文件\n",
  "________________您与电影机的链接暂时中断了\n": "                您与电影机的链接暂时中断了\n",
  "____________________回到首页\n": "                    回到首页\n",
  "____________________________随时随地，专属电影机，创作不受限\n": "                            随时随地，专属电影机，创作不受限\n",
  "注册": "注册",
  "____________________________________________已有账号？\n": "                                            已有账号？\n",
  "____________________________________________________现在登录\n": "                                                    现在登录\n",
  "____________________________________________________________密码\n": "                                                            密码\n",
  "____________________________________________________@click=\"register\">注册": "                                                    @click=\"register\">注册",
  "document.title_=_'注册';\n": "document.title = '注册';\n",
  "________show_toast_duration('请输入有效的邮箱！',_3000)\n": "        show_toast_duration('请输入有效的邮箱！', 3000)\n",
  "________show_toast_duration('请输入有效的邮箱和密码！',_3000)\n": "        show_toast_duration('请输入有效的邮箱和密码！', 3000)\n",
  "____//_获取\n": "    // 获取\n"
}